### ISSUE TITLE
[Question] Time slicing?

### ISSUE THREAD

**Issue by No3371** [Sasai-Kudasai-BM/Water-Physics-Overhaul#1]
Hey, just came from a reference on FluidPhysics repo, surprisingly found this just release an alpha! And it looks promising😄 !

FluidPhysics is a nice mod but the overall experience is kinda ruined by the fact that it always destroy server tps when a player gets near a submarine canyon or accidentally open up a cave to a river, it will just try to process all the water blocks, which can basically cut down tps to one digit or even kill the server.

I'm wondering does WPO has a solution to this problem like time-slicing or somerthing.

**Comment by Sasai-Kudasai-BM** [comment]
Great question.
This problem was partially solved already in the first version of PhysEx.
The main feature of the latest update is the strict time limit for fluid processing.
Now the tps cannot fall due to a large amount of processed processing.
![2021-04-06_142739](https://user-images.githubusercontent.com/68680203/113674291-3d4b7f80-96e4-11eb-864b-c1ed2e8ca6c2.png)
New algorithm uses only remaining tick time.

**Comment by No3371** [comment]
Nice, that's better then I expected, using the already existing remaining tick time sounds way better then implementing a extra block counter. 💯
